using StardewValley;
using System.Linq;
using SVObject = StardewValley.Object;

namespace Randomizer;

public class LightningRodRandomizer
{
    /// <summary>
    /// Intended to be called at the END of the day (else ONLY the simulated strikes will change)
    /// Changes the output of all lightning rods that were struck on this day
    /// </summary>
    public static void Randomize()
    {
        if (!Globals.Config.LightningRod.Randomize) { return; }

        Farm farm = Game1.getFarm();
        var lightningRodId = BigCraftableIndexes.LightningRod.GetItem().QualifiedId;
        var batteryId = ObjectIndexes.Battery.GetItem().QualifiedId;
        var rng = RNG.GetDailyRNG(nameof(LightningRodRandomizer));

        // The filters work as follows:
        // - All lightning rods...
        // - That are not yet ready to harvest (i.e. were struck today)...
        // - That contain a battery (as a failsafe - probably not necessary)
        foreach (SVObject lightningRod in farm.objects.Values
            .Where(obj =>
                obj.QualifiedItemId == lightningRodId &&
                obj.readyForHarvest?.Value == false &&
                obj.heldObject?.Value?.QualifiedItemId == batteryId))
        {
            lightningRod.heldObject.Value = ItemRegistry
                .Create<SVObject>(GetNewLightningRodHeldItemId(rng));

            // This must be set so the game won't overwrite our item with a battery
            lightningRod.readyForHarvest.Value = true;
        }
    }

    /// <summary>
    /// Gets a new item to be generated by the lightning rod, weighted by
    /// the values in the settings
    /// </summary>
    /// <param name="rng">The RNG to use</param>
    /// <returns>The qualified id of the generated item</returns>
    private static string GetNewLightningRodHeldItemId(RNG rng)
    {
        var fullWeight =
            Globals.Config.LightningRod.BatteryWeight +
            Globals.Config.LightningRod.ObjectWeight +
            Globals.Config.LightningRod.BigCraftableWeight +
            Globals.Config.LightningRod.FurnitureWeight;

        var highestBatteryValue = Globals.Config.LightningRod.BatteryWeight;
        var highestObjectValue = Globals.Config.LightningRod.ObjectWeight + highestBatteryValue;
        var highestBigCraftableValue = Globals.Config.LightningRod.BigCraftableWeight + highestObjectValue;
        var highestFurnitureValue = Globals.Config.LightningRod.FurnitureWeight + highestBigCraftableValue;

        var rngValue = rng.NextIntWithinRange(1, fullWeight);

        if (CheckWeightedValue(highestBatteryValue, rngValue))
        {
            return ObjectIndexes.Battery.GetItem().QualifiedId;
        }

        if (CheckWeightedValue(highestObjectValue, rngValue))
        {
            return rng.GetRandomValueFromList(
                ItemList.Items.Values.Where(item => !item.IsRing).ToList()).QualifiedId;
        }

        if (CheckWeightedValue(highestBigCraftableValue, rngValue))
        {
            return BigCraftableFunctions.GetRandomBigCraftableQualifiedId(rng);
        }

        if (CheckWeightedValue(highestFurnitureValue, rngValue))
        {
            return FurnitureFunctions.GetRandomFurnitureQualifiedId(rng);
        }

        // Failsafe in case all weights are 0
        return ObjectIndexes.Battery.GetItem().QualifiedId;
    }

    /// <summary>
    /// Checks whether we rolled the value within the highest weight given
    /// Also checks that the weight is not zero, as that means the user doesn't want this item type to exist
    /// </summary>
    /// <param name="highestWeight">The highest weight</param>
    /// <param name="rngValue">The value we rolled</param>
    /// <returns>True if we rolled it; false otherwise</returns>
    private static bool CheckWeightedValue(int highestWeight, int rngValue)
        => highestWeight > 0 && rngValue <= highestWeight;
}
